site_name: Djali's WotR Hub 
theme:
  name: material
nav:
  - Home: index.md
  - Deep Dive Guides:
    - Shared Experience: Guides/SharedXP/active_xp.md
    - Shared Experience Addendum: Guides/SharedXP/wotr_graphs.md
    - Feud of the Faithful: Guides/Feud/feud.md
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/pathfinder.css
